---
driver:
  forward_agent: yes
  name: vagrant
  gui: true
  vm_hostname:
  network:
  - ["private_network", {ip: "192.168.56.30"}]
  # Mount local /Users/apop/chef-kits folder as c:\share on the VM  
  synced_folders:
  - ['/Users/apop/chef-kits', 'c:/share', 'disabled: false']
  customize:
    cpus: 2
    memory: 4096

transport:
  name: winrm

provisioner:
  name: chef_zero

platforms:
  - name: windows2012
    driver_config:
      box: win2012r2
    provisioner:
      require_chef_omnibus: 12.0.3

suites:
  - name: default
    run_list:
      - recipe[mywin-cookbook::default]
      - recipe[mywin-cookbook::upgrade_client]
    attributes:
      mywin-cookbook:
        chef_package: file:///c:/share/chef/chef-client-12.2.1-1.msi

