transport:
  name: winrm

provisioner:
  name: chef_zero
  #require_chef_omnibus: 11.16.4
  # Obtained from https://www.chef.io/chef/metadata?p=windows&m=x86_64&pv=2012r2&v=12.2.1
  chef_omnibus_url: 'http://10.0.2.2:8000/rhel_install.sh'
  chef_metadata_url: 'file:///c:/share/chef/metadata/windows_v12.4.0.txt'
  client_rb:
    # Use :enabled, :disabled or :audit_only to run the ServerSpec tests in the recipes
    audit_mode: :disabled
    minimal_ohai: true

#driver_config:
  # I don't login often, but when I do, I do it as root
  #username: administrator
  #password: vagrant

driver:
  forward_agent: yes
  name: vagrant
  gui: true
  vm_hostname:
  network:
  - ["private_network", {ip: "192.168.56.30"}]
  # Mount local /Users/apop/chef-kits folder as c:\share on the VM
  synced_folders:
  - ['/Users/andrewdufour/chef-kits', 'c:/share', 'disabled: false']
  customize:
    cpus: 2
    memory: 4096

platforms:
  - name: windows2012
    driver_config:
      box: opentable/win-2012r2-standard-amd64-nocm
  #- name: centos-6.5

suites:
  - name: default
    run_list:
      #- recipe[mywin-cookbook::default]
      #- recipe[mywin-cookbook::install_notepad_pp]
      #- recipe[mywin-cookbook::sample_dsc]
      #- recipe[mywin-cookbook::install_conemu]
      #- recipe[chef-client::task]
      #- recipe[mywin-cookbook::sandbox]
      #- recipe[mywin-cookbook::test]
    attributes:
      mywin-cookbook:
        chef_package: 'file:///c:/share/chef/chef-client-12.4.0-1.msi'
      powershell:
        powershell5:
          url: 'file:///c:/share/windows/WindowsBlue-KB3037315-x64.msu'
          checksum: '9a24de7b85fae96a87188a7fdaab27da3bc90d89426594cdc5f962234a61b7bd'
#      chef_client:
#        task:
#          password: test
